using EM.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EM.Data.Seeding
{
    public static class CitySeed
    {
        public static List<City> GetCities()
        {
            return new List<City>
            {
                        new City { Id = 1, Name = "North and Middle Andaman", StateId = 32 },
                        new City { Id = 2, Name = "South Andaman", StateId = 32 },
                        new City { Id = 3, Name = "Nicobar", StateId = 32 },
                        new City { Id = 4, Name = "Adilabad", StateId = 1 },
                        new City { Id = 5, Name = "Anantapur", StateId = 1 },
                        new City { Id = 6, Name = "Chittoor", StateId = 1 },
                        new City { Id = 7, Name = "East Godavari", StateId = 1 },
                        new City { Id = 8, Name = "Guntur", StateId = 1 },
                        new City { Id = 9, Name = "Hyderabad", StateId = 1 },
                        new City { Id = 10, Name = "Kadapa", StateId = 1 },
                        new City { Id = 11, Name = "Karimnagar", StateId = 1 },
                        new City { Id = 12, Name = "Khammam", StateId = 1 },
                        new City { Id = 13, Name = "Krishna", StateId = 1 },
                        new City { Id = 14, Name = "Kurnool", StateId = 1 },
                        new City { Id = 15, Name = "Mahbubnagar", StateId = 1 },
                        new City { Id = 16, Name = "Medak", StateId = 1 },
                        new City { Id = 17, Name = "Nalgonda", StateId = 1 },
                        new City { Id = 18, Name = "Nellore", StateId = 1 },
                        new City { Id = 19, Name = "Nizamabad", StateId = 1 },
                        new City { Id = 20, Name = "Prakasam", StateId = 1 },
                        new City { Id = 21, Name = "Rangareddi", StateId = 1 },
                        new City { Id = 22, Name = "Srikakulam", StateId = 1 },
                        new City { Id = 23, Name = "Vishakhapatnam", StateId = 1 },
                        new City { Id = 24, Name = "Vizianagaram", StateId = 1 },
                        new City { Id = 25, Name = "Warangal", StateId = 1 },
                        new City { Id = 26, Name = "West Godavari", StateId = 1 },
                        new City { Id = 27, Name = "Anjaw", StateId = 3 },
                        new City { Id = 28, Name = "Changlang", StateId = 3 },
                        new City { Id = 29, Name = "East Kameng", StateId = 3 },
                        new City { Id = 30, Name = "Lohit", StateId = 3 },
                        new City { Id = 31, Name = "Lower Subansiri", StateId = 3 },
                        new City { Id = 32, Name = "Papum Pare", StateId = 3 },
                        new City { Id = 33, Name = "Tirap", StateId = 3 },
                        new City { Id = 34, Name = "Dibang Valley", StateId = 3 },
                        new City { Id = 35, Name = "Upper Subansiri", StateId = 3 },
                        new City { Id = 36, Name = "West Kameng", StateId = 3 },
                        new City { Id = 37, Name = "Barpeta", StateId = 2 },
                        new City { Id = 38, Name = "Bongaigaon", StateId = 2 },
                        new City { Id = 39, Name = "Cachar", StateId = 2 },
                        new City { Id = 40, Name = "Darrang", StateId = 2 },
                        new City { Id = 41, Name = "Dhemaji", StateId = 2 },
                        new City { Id = 42, Name = "Dhubri", StateId = 2 },
                        new City { Id = 43, Name = "Dibrugarh", StateId = 2 },
                        new City { Id = 44, Name = "Goalpara", StateId = 2 },
                        new City { Id = 45, Name = "Golaghat", StateId = 2 },
                        new City { Id = 46, Name = "Hailakandi", StateId = 2 },
                        new City { Id = 47, Name = "Jorhat", StateId = 2 },
                        new City { Id = 48, Name = "Karbi Anglong", StateId = 2 },
                        new City { Id = 49, Name = "Karimganj", StateId = 2 },
                        new City { Id = 50, Name = "Kokrajhar", StateId = 2 },
                        new City { Id = 51, Name = "Lakhimpur", StateId = 2 },
                        new City { Id = 52, Name = "Marigaon", StateId = 2 },
                        new City { Id = 53, Name = "Nagaon", StateId = 2 },
                        new City { Id = 54, Name = "Nalbari", StateId = 2 },
                        new City { Id = 55, Name = "North Cachar Hills", StateId = 2 },
                        new City { Id = 56, Name = "Sibsagar", StateId = 2 },
                        new City { Id = 57, Name = "Sonitpur", StateId = 2 },
                        new City { Id = 58, Name = "Tinsukia", StateId = 2 },
                        new City { Id = 59, Name = "Araria", StateId = 4 },
                        new City { Id = 60, Name = "Aurangabad", StateId = 4 },
                        new City { Id = 61, Name = "Banka", StateId = 4 },
                        new City { Id = 62, Name = "Begusarai", StateId = 4 },
                        new City { Id = 63, Name = "Bhagalpur", StateId = 4 },
                        new City { Id = 64, Name = "Bhojpur", StateId = 4 },
                        new City { Id = 65, Name = "Buxar", StateId = 4 },
                        new City { Id = 66, Name = "Darbhanga", StateId = 4 },
                        new City { Id = 67, Name = "Purba Champaran", StateId = 4 },
                        new City { Id = 68, Name = "Gaya", StateId = 4 },
                        new City { Id = 69, Name = "Gopalganj", StateId = 4 },
                        new City { Id = 70, Name = "Jamui", StateId = 4 },
                        new City { Id = 71, Name = "Jehanabad", StateId = 4 },
                        new City { Id = 72, Name = "Khagaria", StateId = 4 },
                        new City { Id = 73, Name = "Kishanganj", StateId = 4 },
                        new City { Id = 74, Name = "Kaimur", StateId = 4 },
                        new City { Id = 75, Name = "Katihar", StateId = 4 },
                        new City { Id = 76, Name = "Lakhisarai", StateId = 4 },
                        new City { Id = 77, Name = "Madhubani", StateId = 4 },
                        new City { Id = 78, Name = "Munger", StateId = 4 },
                        new City { Id = 79, Name = "Madhepura", StateId = 4 },
                        new City { Id = 80, Name = "Muzaffarpur", StateId = 4 },
                        new City { Id = 81, Name = "Nalanda", StateId = 4 },
                        new City { Id = 82, Name = "Nawada", StateId = 4 },
                        new City { Id = 83, Name = "Patna", StateId = 4 },
                        new City { Id = 84, Name = "Purnia", StateId = 4 },
                        new City { Id = 85, Name = "Rohtas", StateId = 4 },
                        new City { Id = 86, Name = "Saharsa", StateId = 4 },
                        new City { Id = 87, Name = "Samastipur", StateId = 4 },
                        new City { Id = 88, Name = "Sheohar", StateId = 4 },
                        new City { Id = 89, Name = "Sheikhpura", StateId = 4 },
                        new City { Id = 90, Name = "Saran", StateId = 4 },
                        new City { Id = 91, Name = "Sitamarhi", StateId = 4 },
                        new City { Id = 92, Name = "Supaul", StateId = 4 },
                        new City { Id = 93, Name = "Siwan", StateId = 4 },
                        new City { Id = 94, Name = "Vaishali", StateId = 4 },
                        new City { Id = 95, Name = "Pashchim Champaran", StateId = 4 },
                        new City { Id = 96, Name = "Bastar", StateId = 35 },
                        new City { Id = 97, Name = "Bilaspur", StateId = 35 },
                        new City { Id = 98, Name = "Dantewada", StateId = 35 },
                        new City { Id = 99, Name = "Dhamtari", StateId = 35 },
                        new City { Id = 100, Name = "Durg", StateId = 35 },
                        new City { Id = 101, Name = "Jashpur", StateId = 35 },
                        new City { Id = 102, Name = "Janjgir-Champa", StateId = 35 },
                        new City { Id = 103, Name = "Korba", StateId = 35 },
                        new City { Id = 104, Name = "Koriya", StateId = 35 },
                        new City { Id = 105, Name = "Kanker", StateId = 35 },
                        new City { Id = 106, Name = "Kawardha", StateId = 35 },
                        new City { Id = 107, Name = "Mahasamund", StateId = 35 },
                        new City { Id = 108, Name = "Raigarh", StateId = 35 },
                        new City { Id = 109, Name = "Rajnandgaon", StateId = 35 },
                        new City { Id = 110, Name = "Raipur", StateId = 35 },
                        new City { Id = 111, Name = "Surguja", StateId = 35 },
                        new City { Id = 112, Name = "Diu", StateId = 29 },
                        new City { Id = 113, Name = "Daman", StateId = 29 },
                        new City { Id = 114, Name = "Central Delhi", StateId = 25 },
                        new City { Id = 115, Name = "East Delhi", StateId = 25 },
                        new City { Id = 116, Name = "New Delhi", StateId = 25 },
                        new City { Id = 117, Name = "North Delhi", StateId = 25 },
                        new City { Id = 118, Name = "North East Delhi", StateId = 25 },
                        new City { Id = 119, Name = "North West Delhi", StateId = 25 },
                        new City { Id = 120, Name = "South Delhi", StateId = 25 },
                        new City { Id = 121, Name = "South West Delhi", StateId = 25 },
                        new City { Id = 122, Name = "West Delhi", StateId = 25 },
                        new City { Id = 123, Name = "North Goa", StateId = 26 },
                        new City { Id = 124, Name = "South Goa", StateId = 26 },
                        new City { Id = 125, Name = "Ahmedabad", StateId = 5 },
                        new City { Id = 126, Name = "Amreli District", StateId = 5 },
                        new City { Id = 127, Name = "Anand", StateId = 5 },
                        new City { Id = 128, Name = "Banaskantha", StateId = 5 },
                        new City { Id = 129, Name = "Bharuch", StateId = 5 },
                        new City { Id = 130, Name = "Bhavnagar", StateId = 5 },
                        new City { Id = 131, Name = "Dahod", StateId = 5 },
                        new City { Id = 132, Name = "The Dangs", StateId = 5 },
                        new City { Id = 133, Name = "Gandhinagar", StateId = 5 },
                        new City { Id = 134, Name = "Jamnagar", StateId = 5 },
                        new City { Id = 135, Name = "Junagadh", StateId = 5 },
                        new City { Id = 136, Name = "Kutch", StateId = 5 },
                        new City { Id = 137, Name = "Kheda", StateId = 5 },
                        new City { Id = 138, Name = "Mehsana", StateId = 5 },
                        new City { Id = 139, Name = "Narmada", StateId = 5 },
                        new City { Id = 140, Name = "Navsari", StateId = 5 },
                        new City { Id = 141, Name = "Patan", StateId = 5 },
                        new City { Id = 142, Name = "Panchmahal", StateId = 5 },
                        new City { Id = 143, Name = "Porbandar", StateId = 5 },
                        new City { Id = 144, Name = "Rajkot", StateId = 5 },
                        new City { Id = 145, Name = "Sabarkantha", StateId = 5 },
                        new City { Id = 146, Name = "Surendranagar", StateId = 5 },
                        new City { Id = 147, Name = "Surat", StateId = 5 },
                        new City { Id = 148, Name = "Vadodara", StateId = 5 },
                        new City { Id = 149, Name = "Valsad", StateId = 5 },
                        new City { Id = 150, Name = "Ambala", StateId = 6 },
                        new City { Id = 151, Name = "Bhiwani", StateId = 6 },
                        new City { Id = 152, Name = "Faridabad", StateId = 6 },
                        new City { Id = 153, Name = "Fatehabad", StateId = 6 },
                        new City { Id = 154, Name = "Gurgaon", StateId = 6 },
                        new City { Id = 155, Name = "Hissar", StateId = 6 },
                        new City { Id = 156, Name = "Jhajjar", StateId = 6 },
                        new City { Id = 157, Name = "Jind", StateId = 6 },
                        new City { Id = 158, Name = "Karnal", StateId = 6 },
                        new City { Id = 159, Name = "Kaithal", StateId = 6 },
                        new City { Id = 160, Name = "Kurukshetra", StateId = 6 },
                        new City { Id = 161, Name = "Mahendragarh", StateId = 6 },
                        new City { Id = 162, Name = "Mewat", StateId = 6 },
                        new City { Id = 163, Name = "Panchkula", StateId = 6 },
                        new City { Id = 164, Name = "Panipat", StateId = 6 },
                        new City { Id = 165, Name = "Rewari", StateId = 6 },
                        new City { Id = 166, Name = "Rohtak", StateId = 6 },
                        new City { Id = 167, Name = "Sirsa", StateId = 6 },
                        new City { Id = 168, Name = "Sonepat", StateId = 6 },
                        new City { Id = 169, Name = "Yamuna Nagar", StateId = 6 },
                        new City { Id = 170, Name = "Palwal", StateId = 6 },
                        new City { Id = 171, Name = "Bilaspur", StateId = 7 },
                        new City { Id = 172, Name = "Chamba", StateId = 7 },
                        new City { Id = 173, Name = "Hamirpur", StateId = 7 },
                        new City { Id = 174, Name = "Kangra", StateId = 7 },
                        new City { Id = 175, Name = "Kinnaur", StateId = 7 },
                        new City { Id = 176, Name = "Kulu", StateId = 7 },
                        new City { Id = 177, Name = "Lahaul and Spiti", StateId = 7 },
                        new City { Id = 178, Name = "Mandi", StateId = 7 },
                        new City { Id = 179, Name = "Shimla", StateId = 7 },
                        new City { Id = 180, Name = "Sirmaur", StateId = 7 },
                        new City { Id = 181, Name = "Solan", StateId = 7 },
                        new City { Id = 182, Name = "Una", StateId = 7 },
                        new City { Id = 183, Name = "Anantnag", StateId = 8 },
                        new City { Id = 184, Name = "Badgam", StateId = 8 },
                        new City { Id = 185, Name = "Bandipore", StateId = 8 },
                        new City { Id = 186, Name = "Baramula", StateId = 8 },
                        new City { Id = 187, Name = "Doda", StateId = 8 },
                        new City { Id = 188, Name = "Jammu", StateId = 8 },
                        new City { Id = 189, Name = "Kargil", StateId = 8 },
                        new City { Id = 190, Name = "Kathua", StateId = 8 },
                        new City { Id = 191, Name = "Kupwara", StateId = 8 },
                        new City { Id = 192, Name = "Leh", StateId = 8 },
                        new City { Id = 193, Name = "Poonch", StateId = 8 },
                        new City { Id = 194, Name = "Pulwama", StateId = 8 },
                        new City { Id = 195, Name = "Rajauri", StateId = 8 },
                        new City { Id = 196, Name = "Srinagar", StateId = 8 },
                        new City { Id = 197, Name = "Samba", StateId = 8 },
                        new City { Id = 198, Name = "Udhampur", StateId = 8 },
                        new City { Id = 199, Name = "Bokaro", StateId = 34 },
                        new City { Id = 200, Name = "Chatra", StateId = 34 },
                        new City { Id = 201, Name = "Deoghar", StateId = 34 },
                        new City { Id = 202, Name = "Dhanbad", StateId = 34 },
                        new City { Id = 203, Name = "Dumka", StateId = 34 },
                        new City { Id = 204, Name = "Purba Singhbhum", StateId = 34 },
                        new City { Id = 205, Name = "Garhwa", StateId = 34 },
                        new City { Id = 206, Name = "Giridih", StateId = 34 },
                        new City { Id = 207, Name = "Godda", StateId = 34 },
                        new City { Id = 208, Name = "Gumla", StateId = 34 },
                        new City { Id = 209, Name = "Hazaribagh", StateId = 34 },
                        new City { Id = 210, Name = "Koderma", StateId = 34 },
                        new City { Id = 211, Name = "Lohardaga", StateId = 34 },
                        new City { Id = 212, Name = "Pakur", StateId = 34 },
                        new City { Id = 213, Name = "Palamu", StateId = 34 },
                        new City { Id = 214, Name = "Ranchi", StateId = 34 },
                        new City { Id = 215, Name = "Sahibganj", StateId = 34 },
                        new City { Id = 216, Name = "Seraikela and Kharsawan", StateId = 34 },
                        new City { Id = 217, Name = "Pashchim Singhbhum", StateId = 34 },
                        new City { Id = 218, Name = "Ramgarh", StateId = 34 },
                        new City { Id = 219, Name = "Bidar", StateId = 9 },
                        new City { Id = 220, Name = "Belgaum", StateId = 9 },
                        new City { Id = 221, Name = "Bijapur", StateId = 9 },
                        new City { Id = 222, Name = "Bagalkot", StateId = 9 },
                        new City { Id = 223, Name = "Bellary", StateId = 9 },
                        new City { Id = 224, Name = "Bangalore Rural District", StateId = 9 },
                        new City { Id = 225, Name = "Bangalore Urban District", StateId = 9 },
                        new City { Id = 226, Name = "Chamarajnagar", StateId = 9 },
                        new City { Id = 227, Name = "Chikmagalur", StateId = 9 },
                        new City { Id = 228, Name = "Chitradurga", StateId = 9 },
                        new City { Id = 229, Name = "Davanagere", StateId = 9 },
                        new City { Id = 230, Name = "Dharwad", StateId = 9 },
                        new City { Id = 231, Name = "Dakshina Kannada", StateId = 9 },
                        new City { Id = 232, Name = "Gadag", StateId = 9 },
                        new City { Id = 233, Name = "Gulbarga", StateId = 9 },
                        new City { Id = 234, Name = "Hassan", StateId = 9 },
                        new City { Id = 235, Name = "Haveri District", StateId = 9 },
                        new City { Id = 236, Name = "Kodagu", StateId = 9 },
                        new City { Id = 237, Name = "Kolar", StateId = 9 },
                        new City { Id = 238, Name = "Koppal", StateId = 9 },
                        new City { Id = 239, Name = "Mandya", StateId = 9 },
                        new City { Id = 240, Name = "Mysore", StateId = 9 },
                        new City { Id = 241, Name = "Raichur", StateId = 9 },
                        new City { Id = 242, Name = "Shimoga", StateId = 9 },
                        new City { Id = 243, Name = "Tumkur", StateId = 9 },
                        new City { Id = 244, Name = "Udupi", StateId = 9 },
                        new City { Id = 245, Name = "Uttara Kannada", StateId = 9 },
                        new City { Id = 246, Name = "Ramanagara", StateId = 9 },
                        new City { Id = 247, Name = "Chikballapur", StateId = 9 },
                        new City { Id = 248, Name = "Yadagiri", StateId = 9 },
                        new City { Id = 249, Name = "Alappuzha", StateId = 10 },
                        new City { Id = 250, Name = "Ernakulam", StateId = 10 },
                        new City { Id = 251, Name = "Idukki", StateId = 10 },
                        new City { Id = 252, Name = "Kollam", StateId = 10 },
                        new City { Id = 253, Name = "Kannur", StateId = 10 },
                        new City { Id = 254, Name = "Kasaragod", StateId = 10 },
                        new City { Id = 255, Name = "Kottayam", StateId = 10 },
                        new City { Id = 256, Name = "Kozhikode", StateId = 10 },
                        new City { Id = 257, Name = "Malappuram", StateId = 10 },
                        new City { Id = 258, Name = "Palakkad", StateId = 10 },
                        new City { Id = 259, Name = "Pathanamthitta", StateId = 10 },
                        new City { Id = 260, Name = "Thrissur", StateId = 10 },
                        new City { Id = 261, Name = "Thiruvananthapuram", StateId = 10 },
                        new City { Id = 262, Name = "Wayanad", StateId = 10 },
                        new City { Id = 263, Name = "Alirajpur", StateId = 11 },
                        new City { Id = 264, Name = "Anuppur", StateId = 11 },
                        new City { Id = 265, Name = "Ashok Nagar", StateId = 11 },
                        new City { Id = 266, Name = "Balaghat", StateId = 11 },
                        new City { Id = 267, Name = "Barwani", StateId = 11 },
                        new City { Id = 268, Name = "Betul", StateId = 11 },
                        new City { Id = 269, Name = "Bhind", StateId = 11 },
                        new City { Id = 270, Name = "Bhopal", StateId = 11 },
                        new City { Id = 271, Name = "Burhanpur", StateId = 11 },
                        new City { Id = 272, Name = "Chhatarpur", StateId = 11 },
                        new City { Id = 273, Name = "Chhindwara", StateId = 11 },
                        new City { Id = 274, Name = "Damoh", StateId = 11 },
                        new City { Id = 275, Name = "Datia", StateId = 11 },
                        new City { Id = 276, Name = "Dewas", StateId = 11 },
                        new City { Id = 277, Name = "Dhar", StateId = 11 },
                        new City { Id = 278, Name = "Dindori", StateId = 11 },
                        new City { Id = 279, Name = "Guna", StateId = 11 },
                        new City { Id = 280, Name = "Gwalior", StateId = 11 },
                        new City { Id = 281, Name = "Harda", StateId = 11 },
                        new City { Id = 282, Name = "Hoshangabad", StateId = 11 },
                        new City { Id = 283, Name = "Indore", StateId = 11 },
                        new City { Id = 284, Name = "Jabalpur", StateId = 11 },
                        new City { Id = 285, Name = "Jhabua", StateId = 11 },
                        new City { Id = 286, Name = "Katni", StateId = 11 },
                        new City { Id = 287, Name = "Khandwa", StateId = 11 },
                        new City { Id = 288, Name = "Khargone", StateId = 11 },
                        new City { Id = 289, Name = "Mandla", StateId = 11 },
                        new City { Id = 290, Name = "Mandsaur", StateId = 11 },
                        new City { Id = 291, Name = "Morena", StateId = 11 },
                        new City { Id = 292, Name = "Narsinghpur", StateId = 11 },
                        new City { Id = 293, Name = "Neemuch", StateId = 11 },
                        new City { Id = 294, Name = "Panna", StateId = 11 },
                        new City { Id = 295, Name = "Rewa", StateId = 11 },
                        new City { Id = 296, Name = "Rajgarh", StateId = 11 },
                        new City { Id = 297, Name = "Ratlam", StateId = 11 },
                        new City { Id = 298, Name = "Raisen", StateId = 11 },
                        new City { Id = 299, Name = "Sagar", StateId = 11 },
                        new City { Id = 300, Name = "Satna", StateId = 11 },
                        new City { Id = 301, Name = "Sehore", StateId = 11 },
                        new City { Id = 302, Name = "Seoni", StateId = 11 },
                        new City { Id = 303, Name = "Shahdol", StateId = 11 },
                        new City { Id = 304, Name = "Shajapur", StateId = 11 },
                        new City { Id = 305, Name = "Sheopur", StateId = 11 },
                        new City { Id = 306, Name = "Shivpuri", StateId = 11 },
                        new City { Id = 307, Name = "Sidhi", StateId = 11 },
                        new City { Id = 308, Name = "Singrauli", StateId = 11 },
                        new City { Id = 309, Name = "Tikamgarh", StateId = 11 },
                        new City { Id = 310, Name = "Ujjain", StateId = 11 },
                        new City { Id = 311, Name = "Umaria", StateId = 11 },
                        new City { Id = 312, Name = "Vidisha", StateId = 11 },
                        new City { Id = 313, Name = "Ahmednagar", StateId = 12 },
                        new City { Id = 314, Name = "Akola", StateId = 12 },
                        new City { Id = 315, Name = "Amrawati", StateId = 12 },
                        new City { Id = 316, Name = "Aurangabad", StateId = 12 },
                        new City { Id = 317, Name = "Bhandara", StateId = 12 },
                        new City { Id = 318, Name = "Beed", StateId = 12 },
                        new City { Id = 319, Name = "Buldhana", StateId = 12 },
                        new City { Id = 320, Name = "Chandrapur", StateId = 12 },
                        new City { Id = 321, Name = "Dhule", StateId = 12 },
                        new City { Id = 322, Name = "Gadchiroli", StateId = 12 },
                        new City { Id = 323, Name = "Gondiya", StateId = 12 },
                        new City { Id = 324, Name = "Hingoli", StateId = 12 },
                        new City { Id = 325, Name = "Jalgaon", StateId = 12 },
                        new City { Id = 326, Name = "Jalna", StateId = 12 },
                        new City { Id = 327, Name = "Kolhapur", StateId = 12 },
                        new City { Id = 328, Name = "Latur", StateId = 12 },
                        new City { Id = 329, Name = "Mumbai City", StateId = 12 },
                        new City { Id = 330, Name = "Mumbai suburban", StateId = 12 },
                        new City { Id = 331, Name = "Nandurbar", StateId = 12 },
                        new City { Id = 332, Name = "Nanded", StateId = 12 },
                        new City { Id = 333, Name = "Nagpur", StateId = 12 },
                        new City { Id = 334, Name = "Nashik", StateId = 12 },
                        new City { Id = 335, Name = "Osmanabad", StateId = 12 },
                        new City { Id = 336, Name = "Parbhani", StateId = 12 },
                        new City { Id = 337, Name = "Pune", StateId = 12 },
                        new City { Id = 338, Name = "Raigad", StateId = 12 },
                        new City { Id = 339, Name = "Ratnagiri", StateId = 12 },
                        new City { Id = 340, Name = "Sindhudurg", StateId = 12 },
                        new City { Id = 341, Name = "Sangli", StateId = 12 },
                        new City { Id = 342, Name = "Solapur", StateId = 12 },
                        new City { Id = 343, Name = "Satara", StateId = 12 },
                        new City { Id = 344, Name = "Thane", StateId = 12 },
                        new City { Id = 345, Name = "Wardha", StateId = 12 },
                        new City { Id = 346, Name = "Washim", StateId = 12 },
                        new City { Id = 347, Name = "Yavatmal", StateId = 12 },
                        new City { Id = 348, Name = "Bishnupur", StateId = 13 },
                        new City { Id = 349, Name = "Churachandpur", StateId = 13 },
                        new City { Id = 350, Name = "Chandel", StateId = 13 },
                        new City { Id = 351, Name = "Imphal East", StateId = 13 },
                        new City { Id = 352, Name = "Senapati", StateId = 13 },
                        new City { Id = 353, Name = "Tamenglong", StateId = 13 },
                        new City { Id = 354, Name = "Thoubal", StateId = 13 },
                        new City { Id = 355, Name = "Ukhrul", StateId = 13 },
                        new City { Id = 356, Name = "Imphal West", StateId = 13 },
                        new City { Id = 357, Name = "East Garo Hills", StateId = 14 },
                        new City { Id = 358, Name = "East Khasi Hills", StateId = 14 },
                        new City { Id = 359, Name = "Jaintia Hills", StateId = 14 },
                        new City { Id = 360, Name = "Ri-Bhoi", StateId = 14 },
                        new City { Id = 361, Name = "South Garo Hills", StateId = 14 },
                        new City { Id = 362, Name = "West Garo Hills", StateId = 14 },
                        new City { Id = 363, Name = "West Khasi Hills", StateId = 14 },
                        new City { Id = 364, Name = "Aizawl", StateId = 15 },
                        new City { Id = 365, Name = "Champhai", StateId = 15 },
                        new City { Id = 366, Name = "Kolasib", StateId = 15 },
                        new City { Id = 367, Name = "Lawngtlai", StateId = 15 },
                        new City { Id = 368, Name = "Lunglei", StateId = 15 },
                        new City { Id = 369, Name = "Mamit", StateId = 15 },
                        new City { Id = 370, Name = "Saiha", StateId = 15 },
                        new City { Id = 371, Name = "Serchhip", StateId = 15 },
                        new City { Id = 372, Name = "Dimapur", StateId = 16 },
                        new City { Id = 373, Name = "Kohima", StateId = 16 },
                        new City { Id = 374, Name = "Mokokchung", StateId = 16 },
                        new City { Id = 375, Name = "Mon", StateId = 16 },
                        new City { Id = 376, Name = "Phek", StateId = 16 },
                        new City { Id = 377, Name = "Tuensang", StateId = 16 },
                        new City { Id = 378, Name = "Wokha", StateId = 16 },
                        new City { Id = 379, Name = "Zunheboto", StateId = 16 },
                        new City { Id = 380, Name = "Angul", StateId = 17 },
                        new City { Id = 381, Name = "Boudh", StateId = 17 },
                        new City { Id = 382, Name = "Bhadrak", StateId = 17 },
                        new City { Id = 383, Name = "Bolangir", StateId = 17 },
                        new City { Id = 384, Name = "Bargarh", StateId = 17 },
                        new City { Id = 385, Name = "Baleswar", StateId = 17 },
                        new City { Id = 386, Name = "Cuttack", StateId = 17 },
                        new City { Id = 387, Name = "Debagarh", StateId = 17 },
                        new City { Id = 388, Name = "Dhenkanal", StateId = 17 },
                        new City { Id = 389, Name = "Ganjam", StateId = 17 },
                        new City { Id = 390, Name = "Gajapati", StateId = 17 },
                        new City { Id = 391, Name = "Jharsuguda", StateId = 17 },
                        new City { Id = 392, Name = "Jajapur", StateId = 17 },
                        new City { Id = 393, Name = "Jagatsinghpur", StateId = 17 },
                        new City { Id = 394, Name = "Khordha", StateId = 17 },
                        new City { Id = 395, Name = "Kendujhar", StateId = 17 },
                        new City { Id = 396, Name = "Kalahandi", StateId = 17 },
                        new City { Id = 397, Name = "Kandhamal", StateId = 17 },
                        new City { Id = 398, Name = "Koraput", StateId = 17 },
                        new City { Id = 399, Name = "Kendrapara", StateId = 17 },
                        new City { Id = 400, Name = "Malkangiri", StateId = 17 },
                        new City { Id = 401, Name = "Mayurbhanj", StateId = 17 },
                        new City { Id = 402, Name = "Nabarangpur", StateId = 17 },
                        new City { Id = 403, Name = "Nuapada", StateId = 17 },
                        new City { Id = 404, Name = "Nayagarh", StateId = 17 },
                        new City { Id = 405, Name = "Puri", StateId = 17 },
                        new City { Id = 406, Name = "Rayagada", StateId = 17 },
                        new City { Id = 407, Name = "Sambalpur", StateId = 17 },
                        new City { Id = 408, Name = "Subarnapur", StateId = 17 },
                        new City { Id = 409, Name = "Sundargarh", StateId = 17 },
                        new City { Id = 410, Name = "Karaikal", StateId = 27 },
                        new City { Id = 411, Name = "Mahe", StateId = 27 },
                        new City { Id = 412, Name = "Puducherry", StateId = 27 },
                        new City { Id = 413, Name = "Yanam", StateId = 27 },
                        new City { Id = 414, Name = "Amritsar", StateId = 18 },
                        new City { Id = 415, Name = "Bathinda", StateId = 18 },
                        new City { Id = 416, Name = "Firozpur", StateId = 18 },
                        new City { Id = 417, Name = "Faridkot", StateId = 18 },
                        new City { Id = 418, Name = "Fatehgarh Sahib", StateId = 18 },
                        new City { Id = 419, Name = "Gurdaspur", StateId = 18 },
                        new City { Id = 420, Name = "Hoshiarpur", StateId = 18 },
                        new City { Id = 421, Name = "Jalandhar", StateId = 18 },
                        new City { Id = 422, Name = "Kapurthala", StateId = 18 },
                        new City { Id = 423, Name = "Ludhiana", StateId = 18 },
                        new City { Id = 424, Name = "Mansa", StateId = 18 },
                        new City { Id = 425, Name = "Moga", StateId = 18 },
                        new City { Id = 426, Name = "Mukatsar", StateId = 18 },
                        new City { Id = 427, Name = "Nawan Shehar", StateId = 18 },
                        new City { Id = 428, Name = "Patiala", StateId = 18 },
                        new City { Id = 429, Name = "Rupnagar", StateId = 18 },
                        new City { Id = 430, Name = "Sangrur", StateId = 18 },
                        new City { Id = 431, Name = "Ajmer", StateId = 19 },
                        new City { Id = 432, Name = "Alwar", StateId = 19 },
                        new City { Id = 433, Name = "Bikaner", StateId = 19 },
                        new City { Id = 434, Name = "Barmer", StateId = 19 },
                        new City { Id = 435, Name = "Banswara", StateId = 19 },
                        new City { Id = 436, Name = "Bharatpur", StateId = 19 },
                        new City { Id = 437, Name = "Baran", StateId = 19 },
                        new City { Id = 438, Name = "Bundi", StateId = 19 },
                        new City { Id = 439, Name = "Bhilwara", StateId = 19 },
                        new City { Id = 440, Name = "Churu", StateId = 19 },
                        new City { Id = 441, Name = "Chittorgarh", StateId = 19 },
                        new City { Id = 442, Name = "Dausa", StateId = 19 },
                        new City { Id = 443, Name = "Dholpur", StateId = 19 },
                        new City { Id = 444, Name = "Dungapur", StateId = 19 },
                        new City { Id = 445, Name = "Ganganagar", StateId = 19 },
                        new City { Id = 446, Name = "Hanumangarh", StateId = 19 },
                        new City { Id = 447, Name = "Juhnjhunun", StateId = 19 },
                        new City { Id = 448, Name = "Jalore", StateId = 19 },
                        new City { Id = 449, Name = "Jodhpur", StateId = 19 },
                        new City { Id = 450, Name = "Jaipur", StateId = 19 },
                        new City { Id = 451, Name = "Jaisalmer", StateId = 19 },
                        new City { Id = 452, Name = "Jhalawar", StateId = 19 },
                        new City { Id = 453, Name = "Karauli", StateId = 19 },
                        new City { Id = 454, Name = "Kota", StateId = 19 },
                        new City { Id = 455, Name = "Nagaur", StateId = 19 },
                        new City { Id = 456, Name = "Pali", StateId = 19 },
                        new City { Id = 457, Name = "Pratapgarh", StateId = 19 },
                        new City { Id = 458, Name = "Rajsamand", StateId = 19 },
                        new City { Id = 459, Name = "Sikar", StateId = 19 },
                        new City { Id = 460, Name = "Sawai Madhopur", StateId = 19 },
                        new City { Id = 461, Name = "Sirohi", StateId = 19 },
                        new City { Id = 462, Name = "Tonk", StateId = 19 },
                        new City { Id = 463, Name = "Udaipur", StateId = 19 },
                        new City { Id = 464, Name = "East Sikkim", StateId = 20 },
                        new City { Id = 465, Name = "North Sikkim", StateId = 20 },
                        new City { Id = 466, Name = "South Sikkim", StateId = 20 },
                        new City { Id = 467, Name = "West Sikkim", StateId = 20 },
                        new City { Id = 468, Name = "Ariyalur", StateId = 21 },
                        new City { Id = 469, Name = "Chennai", StateId = 21 },
                        new City { Id = 470, Name = "Coimbatore", StateId = 21 },
                        new City { Id = 471, Name = "Cuddalore", StateId = 21 },
                        new City { Id = 472, Name = "Dharmapuri", StateId = 21 },
                        new City { Id = 473, Name = "Dindigul", StateId = 21 },
                        new City { Id = 474, Name = "Erode", StateId = 21 },
                        new City { Id = 475, Name = "Kanchipuram", StateId = 21 },
                        new City { Id = 476, Name = "Kanyakumari", StateId = 21 },
                        new City { Id = 477, Name = "Karur", StateId = 21 },
                        new City { Id = 478, Name = "Madurai", StateId = 21 },
                        new City { Id = 479, Name = "Nagapattinam", StateId = 21 },
                        new City { Id = 480, Name = "The Nilgiris", StateId = 21 },
                        new City { Id = 481, Name = "Namakkal", StateId = 21 },
                        new City { Id = 482, Name = "Perambalur", StateId = 21 },
                        new City { Id = 483, Name = "Pudukkottai", StateId = 21 },
                        new City { Id = 484, Name = "Ramanathapuram", StateId = 21 },
                        new City { Id = 485, Name = "Salem", StateId = 21 },
                        new City { Id = 486, Name = "Sivagangai", StateId = 21 },
                        new City { Id = 487, Name = "Tiruppur", StateId = 21 },
                        new City { Id = 488, Name = "Tiruchirappalli", StateId = 21 },
                        new City { Id = 489, Name = "Theni", StateId = 21 },
                        new City { Id = 490, Name = "Tirunelveli", StateId = 21 },
                        new City { Id = 491, Name = "Thanjavur", StateId = 21 },
                        new City { Id = 492, Name = "Thoothukudi", StateId = 21 },
                        new City { Id = 493, Name = "Thiruvallur", StateId = 21 },
                        new City { Id = 494, Name = "Thiruvarur", StateId = 21 },
                        new City { Id = 495, Name = "Tiruvannamalai", StateId = 21 },
                        new City { Id = 496, Name = "Vellore", StateId = 21 },
                        new City { Id = 497, Name = "Villupuram", StateId = 21 },
                        new City { Id = 498, Name = "Dhalai", StateId = 22 },
                        new City { Id = 499, Name = "North Tripura", StateId = 22 },
                        new City { Id = 500, Name = "South Tripura", StateId = 22 },
                        new City { Id = 501, Name = "West Tripura", StateId = 22 },
                        new City { Id = 502, Name = "Almora", StateId = 33 },
                        new City { Id = 503, Name = "Bageshwar", StateId = 33 },
                        new City { Id = 504, Name = "Chamoli", StateId = 33 },
                        new City { Id = 505, Name = "Champawat", StateId = 33 },
                        new City { Id = 506, Name = "Dehradun", StateId = 33 },
                        new City { Id = 507, Name = "Haridwar", StateId = 33 },
                        new City { Id = 508, Name = "Nainital", StateId = 33 },
                        new City { Id = 509, Name = "Pauri Garhwal", StateId = 33 },
                        new City { Id = 510, Name = "Pithoragharh", StateId = 33 },
                        new City { Id = 511, Name = "Rudraprayag", StateId = 33 },
                        new City { Id = 512, Name = "Tehri Garhwal", StateId = 33 },
                        new City { Id = 513, Name = "Udham Singh Nagar", StateId = 33 },
                        new City { Id = 514, Name = "Uttarkashi", StateId = 33 },
                        new City { Id = 515, Name = "Agra", StateId = 23 },
                        new City { Id = 516, Name = "Allahabad", StateId = 23 },
                        new City { Id = 517, Name = "Aligarh", StateId = 23 },
                        new City { Id = 518, Name = "Ambedkar Nagar", StateId = 23 },
                        new City { Id = 519, Name = "Auraiya", StateId = 23 },
                        new City { Id = 520, Name = "Azamgarh", StateId = 23 },
                        new City { Id = 521, Name = "Barabanki", StateId = 23 },
                        new City { Id = 522, Name = "Badaun", StateId = 23 },
                        new City { Id = 523, Name = "Bagpat", StateId = 23 },
                        new City { Id = 524, Name = "Bahraich", StateId = 23 },
                        new City { Id = 525, Name = "Bijnor", StateId = 23 },
                        new City { Id = 526, Name = "Ballia", StateId = 23 },
                        new City { Id = 527, Name = "Banda", StateId = 23 },
                        new City { Id = 528, Name = "Balrampur", StateId = 23 },
                        new City { Id = 529, Name = "Bareilly", StateId = 23 },
                        new City { Id = 530, Name = "Basti", StateId = 23 },
                        new City { Id = 531, Name = "Bulandshahr", StateId = 23 },
                        new City { Id = 532, Name = "Chandauli", StateId = 23 },
                        new City { Id = 533, Name = "Chitrakoot", StateId = 23 },
                        new City { Id = 534, Name = "Deoria", StateId = 23 },
                        new City { Id = 535, Name = "Etah", StateId = 23 },
                        new City { Id = 536, Name = "Kanshiram Nagar", StateId = 23 },
                        new City { Id = 537, Name = "Etawah", StateId = 23 },
                        new City { Id = 538, Name = "Firozabad", StateId = 23 },
                        new City { Id = 539, Name = "Farrukhabad", StateId = 23 },
                        new City { Id = 540, Name = "Fatehpur", StateId = 23 },
                        new City { Id = 541, Name = "Faizabad", StateId = 23 },
                        new City { Id = 542, Name = "Gautam Buddha Nagar", StateId = 23 },
                        new City { Id = 543, Name = "Gonda", StateId = 23 },
                        new City { Id = 544, Name = "Ghazipur", StateId = 23 },
                        new City { Id = 545, Name = "Gorkakhpur", StateId = 23 },
                        new City { Id = 546, Name = "Ghaziabad", StateId = 23 },
                        new City { Id = 547, Name = "Hamirpur", StateId = 23 },
                        new City { Id = 548, Name = "Hardoi", StateId = 23 },
                        new City { Id = 549, Name = "Mahamaya Nagar", StateId = 23 },
                        new City { Id = 550, Name = "Jhansi", StateId = 23 },
                        new City { Id = 551, Name = "Jalaun", StateId = 23 },
                        new City { Id = 552, Name = "Jyotiba Phule Nagar", StateId = 23 },
                        new City { Id = 553, Name = "Jaunpur District", StateId = 23 },
                        new City { Id = 554, Name = "Kanpur Dehat", StateId = 23 },
                        new City { Id = 555, Name = "Kannauj", StateId = 23 },
                        new City { Id = 556, Name = "Kanpur Nagar", StateId = 23 },
                        new City { Id = 557, Name = "Kaushambi", StateId = 23 },
                        new City { Id = 558, Name = "Kushinagar", StateId = 23 },
                        new City { Id = 559, Name = "Lalitpur", StateId = 23 },
                        new City { Id = 560, Name = "Lakhimpur Kheri", StateId = 23 },
                        new City { Id = 561, Name = "Lucknow", StateId = 23 },
                        new City { Id = 562, Name = "Mau", StateId = 23 },
                        new City { Id = 563, Name = "Meerut", StateId = 23 },
                        new City { Id = 564, Name = "Maharajganj", StateId = 23 },
                        new City { Id = 565, Name = "Mahoba", StateId = 23 },
                        new City { Id = 566, Name = "Mirzapur", StateId = 23 },
                        new City { Id = 567, Name = "Moradabad", StateId = 23 },
                        new City { Id = 568, Name = "Mainpuri", StateId = 23 },
                        new City { Id = 569, Name = "Mathura", StateId = 23 },
                        new City { Id = 570, Name = "Muzaffarnagar", StateId = 23 },
                        new City { Id = 571, Name = "Pilibhit", StateId = 23 },
                        new City { Id = 572, Name = "Pratapgarh", StateId = 23 },
                        new City { Id = 573, Name = "Rampur", StateId = 23 },
                        new City { Id = 574, Name = "Rae Bareli", StateId = 23 },
                        new City { Id = 575, Name = "Saharanpur", StateId = 23 },
                        new City { Id = 576, Name = "Sitapur", StateId = 23 },
                        new City { Id = 577, Name = "Shahjahanpur", StateId = 23 },
                        new City { Id = 578, Name = "Sant Kabir Nagar", StateId = 23 },
                        new City { Id = 579, Name = "Siddharthnagar", StateId = 23 },
                        new City { Id = 580, Name = "Sonbhadra", StateId = 23 },
                        new City { Id = 581, Name = "Sant Ravidas Nagar", StateId = 23 },
                        new City { Id = 582, Name = "Sultanpur", StateId = 23 },
                        new City { Id = 583, Name = "Shravasti", StateId = 23 },
                        new City { Id = 584, Name = "Unnao", StateId = 23 },
                        new City { Id = 585, Name = "Varanasi", StateId = 23 },
                        new City { Id = 586, Name = "Birbhum", StateId = 24 },
                        new City { Id = 587, Name = "Bankura", StateId = 24 },
                        new City { Id = 588, Name = "Bardhaman", StateId = 24 },
                        new City { Id = 589, Name = "Darjeeling", StateId = 24 },
                        new City { Id = 590, Name = "Dakshin Dinajpur", StateId = 24 },
                        new City { Id = 591, Name = "Hooghly", StateId = 24 },
                        new City { Id = 592, Name = "Howrah", StateId = 24 },
                        new City { Id = 593, Name = "Jalpaiguri", StateId = 24 },
                        new City { Id = 594, Name = "Cooch Behar", StateId = 24 },
                        new City { Id = 595, Name = "Kolkata", StateId = 24 },
                        new City { Id = 596, Name = "Malda", StateId = 24 },
                        new City { Id = 597, Name = "Midnapore", StateId = 24 },
                        new City { Id = 598, Name = "Murshidabad", StateId = 24 },
                        new City { Id = 599, Name = "Nadia", StateId = 24 },
                        new City { Id = 600, Name = "North 24 Parganas", StateId = 24 },
                        new City { Id = 601, Name = "South 24 Parganas", StateId = 24 },
                        new City { Id = 602, Name = "Purulia", StateId = 24 },
                        new City { Id = 603, Name = "Uttar Dinajpur", StateId = 24 }

            };
        }
    }
}
